name: 'Publish Office Sim'
on:
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run bash script
        run: bash publish.sh
      - name: Publish game
        id: fp-publish
        uses: Final-Parsec/publish-game@v1
        with:
          who-to-greet: 'Zara Nebulon'
      - name: Show output from the publish
        run: echo "The time was ${{ steps.fp-publish.outputs.time }}"