name: 'Publish Office Sim'
on:
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v1
        name: 🤖 Setup Godot
        with:
          version: 4.3.0-stable
          use-dotnet: false
          include-templates: true
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --headless --path game --export-release "Web" build/web/index.html
      - name: Cache build directory
        uses: actions/cache@v3
        with:
          path: build/web
          key: web-build-${{ github.sha }}
      - name: Publish game
        id: fp-publish
        uses: Final-Parsec/publish-game@v1
        with:
          game-name: 'Office Sim'
          asset-directory: build/web
      - name: Show output from the publish
        run: echo "The time was ${{ steps.fp-publish.outputs.time }}"
